### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by VuzzyM** [phrutis/Passphrases-from-file#2]
Он не показывает оба ключа wif(uncompressed,compressed) 

Только compressed wif показывает.

**Comment by phrutis** [comment]
Возьми найденный privat key и конвертируй его сторонней программой, скриптом и т.п.

**Comment by VuzzyM** [comment]
> Возьми найденный privat key и конвертируй его сторонней программой, скриптом и т.п.

хорошо спасибо
